# Generated by Django 4.2.2 on 2023-06-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='expert',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
