# Generated by Django 4.2.2 on 2023-06-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_offers_club_package_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='type',
            new_name='package_type',
        ),
    ]
