# Generated by Django 4.2.2 on 2023-06-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
