# Generated by Django 4.2.2 on 2023-06-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messaget',
            new_name='message',
        ),
    ]
