# Generated by Django 4.2.2 on 2023-06-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_messaget_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.club'),
        ),
    ]
