# Generated by Django 4.2.2 on 2023-06-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_club_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Self_defense ', 'Self Defense '), ('Equestrian', 'Equestrian')], default='Jeddah', max_length=64),
        ),
    ]
