# Generated by Django 4.2.2 on 2023-06-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_club_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='city',
        ),
    ]
