# Generated by Django 4.2.2 on 2023-06-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_comment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='name',
            new_name='coach_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='social_account',
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.club')),
            ],
        ),
    ]
