# Generated by Django 4.2.2 on 2023-06-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='say',
            name='image',
        ),
    ]
