# Generated by Django 4.2.2 on 2023-06-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_club_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_say',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('decription', models.TextField()),
            ],
        ),
    ]
