# Generated by Django 4.2.2 on 2023-06-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_client_say'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client_say',
            new_name='Say',
        ),
    ]
