# Generated by Django 4.2.2 on 2023-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_client_say_say'),
    ]

    operations = [
        migrations.AddField(
            model_name='say',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
