# Generated by Django 4.2.2 on 2023-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_tournament_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('awards', models.CharField(max_length=100)),
            ],
        ),
    ]
