# Generated by Django 4.2.2 on 2023-06-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_subscripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripe',
            name='other',
            field=models.TextField(default='1'),
        ),
    ]
