# Generated by Django 4.2.2 on 2023-06-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offers',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offers',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
