# Generated by Django 4.2.2 on 2023-06-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_subscripe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripe',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.club'),
        ),
    ]
