# Generated by Django 4.2.2 on 2023-06-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_offers_description_alter_offers_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='description',
            field=models.TextField(),
        ),
    ]
