# Generated by Django 4.2.2 on 2023-06-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_offers_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offers',
            name='price',
            field=models.IntegerField(),
        ),
    ]
