# Generated by Django 4.2.2 on 2023-06-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_tournament'),
        ('main_app', '0019_alter_offers_discount_alter_offers_price'),
    ]

    operations = [
    ]
