# Generated by Django 4.2.2 on 2023-06-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_phone_number_alter_profile_age'),
        ('main_app', '0020_subscripe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscripe',
            name='user',
        ),
        migrations.AddField(
            model_name='subscripe',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
