# Generated by Django 4.2.2 on 2023-06-20 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0021_remove_subscripe_user_subscripe_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscripe',
            name='profile',
        ),
        migrations.AddField(
            model_name='subscripe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
