# Generated by Django 4.2.2 on 2023-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_subscripe_profile_subscripe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripe',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
