# Generated by Django 4.2.2 on 2023-06-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_subscripe_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripe',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.tournament'),
        ),
    ]
